styles: Add some styles
fferegrino/study-with-me pull request #1
Opened 2022-06-15 00:25 UTC by Antonio072

Fondo y estilo para el form

2022-06-15 05:42 UTC, fferegrino requested changes

2022-06-15 05:42 UTC, fferegrino commented on study.css
> +     background-color: burlywood;
I would not put any background, at least not for the `study.html` page. The timer's page background should be "transparent". Otherwise, it looks fine :)

2022-06-15 05:42 UTC, fferegrino commented on study.css
> +     background-color: burlywood;
Can you comment these lines again, then we can merge :D

2022-06-15 06:22 UTC, Antonio072 commented on study.css
> +     background-color: burlywood;
Done, I think that in the meantime $background-color could be transparent so there is no need to comment backgrounds, just using the transparent variable

2022-06-16 05:53 UTC, fferegrino commented
Cool :)

2022-06-16 05:53 UTC, merged